services:

  mysql:
    image: mysql:8.4
    container_name: mysql84
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: demo
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    ports: ["3307:3306"]
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      
  php:
    image: php:8.3-fpm
    container_name: php_app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php